# Generated by Django 4.2.1 on 2023-06-07 14:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_or_new', models.CharField(choices=[('Новость', 'Новости'), ('Статья', 'Статьи')], max_length=20)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('article_title_news', models.CharField(max_length=50)),
                ('main_text', models.TextField()),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postnews.author')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postnews.category')),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postnews.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='id_post_category',
            field=models.ManyToManyField(through='postnews.PostCategory', to='postnews.category'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField()),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('rating_comment', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('id_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postnews.post')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
